name: EPG Fetcher

on:
  push:
  schedule:
    - cron: '0 1,3,5,7,9,11,13,15,17,19,21,23 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch EPG Files
      run: |
        rm -f e.xml epg.xml
        curl -o e.xml https://epg.112114.xyz/pp.xml  
        ls -l  
        cat e.xml  
        cp e.xml epg.xml  
        rm -f e.xml

    - name: Show epg.xml content
      run: cat epg.xml  

    - name: Configure Git
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

    - name: Pull remote changes
      run: git pull origin main  

    - name: Add and commit changes
      run: |
        git add epg.xml
        git commit -m "Force update EPG files" --allow-empty  

    - name: Push changes
      run: git push origin main  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
