name: EPG Fetcher

on:
  push:
  schedule:
    - cron: '0 1,3,5,7,9,11,13,15,17,19,21,23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch EPG Files
      run: |
        rm -f e.xml epg.xml 
        curl -o e.xml https://e.erw.cc/e.xml
        cat e.xml > epg.xml
        rm -f e.xml 
        
        # Show the content of the downloaded files for debugging
        ls -l
        cat epg.xml

    - name: Add index.html
      run: |
        echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>EPG Files</title></head><body><h1>Welcome to the EPG Fetcher Site</h1><p>The EPG XML file is available at epg.xml.</p ></body></html>' > index.html
        
        # Show the content of the generated index.html file for debugging
        cat index.html
        git add index.html
        git commit -m "Add index.html for GitHub Pages"

    - name: Push changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
