name: EPG Fetcher

on:
  push:
  schedule:
    - cron: '0 1,3,5,7,9,11,13,15,17,19,21,23 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
  uses: actions/checkout@v3

- name: Remove old file
  run: |
    echo "Removing old file..."
    rm -f epg.xml || { echo "Failed to remove epg.xml"; exit 1; }

- name: Download new file
  run: |
    echo "Downloading new file..."
    curl -o epg.xml https://example.com/epg.xml || { echo "Failed to download epg.xml"; exit 1; }

- name: Configure Git
  run: |
    git config --local user.name "github-actions[bot]"
    git config --local user.email "github-actions[bot]@users.noreply.github.com"

- name: Commit changes
  run: |
    echo "Adding and committing changes..."
    git add epg.xml || { echo "Failed to add epg.xml"; exit 1; }
    git commit -m "EPG Automatic Fetcher." || { echo "Failed to commit changes"; exit 1; }

- name: Push changes
  run: |
    echo "Pushing changes..."
    git push origin main || { echo "Failed to push changes"; exit 1; }
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
