name: EPG Fetcher

on:
  push:
  schedule:
    - cron: '0 1,3,5,7,9,11,13,15,17,19,21,23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python
      run: sudo apt-get install -y python3

    - name: Fetch EPG Files
      run: |
        rm -f e.xml epg.xml epg_part.xml
        
        curl -o e.xml https://e.erw.cc/e.xml
        curl -o epg_part.xml https://assets.livednow.com/epg.xml
        
        python3 merge_xml.py
                
        rm -f e.xml epg_part.xml
        
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        
        git add epg.xml
        git commit -m "EPG Automatic Fetcher."
    
    - name: Push changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
