name: EPG Fetcher

on:
  push:
  schedule:
    - cron: '0 1,3,5,7,9,11,13,15,17,19,21,23 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch EPG Files
      run: |

        rm -f epg.xml epg.xml.gz
        

        wget https://e.erw.cc/e.xml -O e.xml
        wget https://epg.112114.xyz/pp.xml -O epg_part.xml
        

        cat e.xml epg_part.xml > epg.xml
        

        gzip -c epg.xml > epg.xml.gz
        

        rm -f e.xml epg_part.xml


        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        

        git add epg.xml epg.xml.gz
        git commit -m "EPG Automatic Fetcher."
    
       - name: Debug GitHub Token
         run: |
         curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
