name: EPG Fetcher
on:
  push:
  schedule:
    - cron: '00 00,2,4,6,8,10,12,14,18,20,22, * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetcher EPG Files
      run: |
        rm -f epg.xml epg.xml.gz
        wget https://e.erw.cc/e.xml.gz -O e.xml.gz
        wget https://assets.livednow.com/epg.xml -O epg_part.xml
        gzip -d e.xml.gz
        cat e.xml epg_part.xml > epg.xml
        epg.xml.gz
        gzip -c epg.xml > epg.xml.gz
        rm -f e.xml epg_part.xml
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add epg.xml epg.xml.gz
        git commit -m "EPG Automatic Fetcher."
    - name: Push changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
