name: IPTV Scraper Workflow

on:
  schedule:
    - cron: "0 0 * * *"  # 每天凌晨 0 点触发脚本

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        run: git clone https://github.com/username/iptv-scraper.git

      - name: Install Dependencies
        run: |
          cd iptv-scraper
          pip install -r requirements.txt

      - name: Run Script
        run: python main_script.py

      - name: Upload Files to GitHub
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-upload generated IPTV data"
          git push origin main
