name: Run main.py

on:
  schedule:
    - cron: "0 17 * * *"  # 每天下午5点自动触发
  workflow_dispatch:   # 也可以手动触发

jobs:
  run_main:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install requests
          pip install aiohttp

      - name: Run main.py
        run: python main.py
